server:
  port: 8083

services:
  assets:
    url: http://localhost:8081
  user-profile:
    url: http://localhost:8082

spring:
  application:
    name: recommendation-service

logging:
  level:
    root: INFO
    com.datarium.recommendation: DEBUG